In [1]:
"""NumPy - Numerical python
Jan 20^24:- first class for Numpy"""

'NumPy - Numerical python\nJan 20^24:- first class for Numpy'

In [2]:
import numpy as np #2005 by Travis Oliphant, numpy is built on C++(Fastest programming language)

In [3]:
np.__version__

'1.23.5'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [5]:
#Why NumPy
#-mathematical function
#Faster as compared to others

In [6]:
l = [1,2,3,4,5]

In [7]:
arr = np.array(l)

In [8]:
type(np.array(l))

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
#ndarray = n dimensional array
#Array is the way numpy stores the data
#Array stores only same type of data while List can store heterogeneous data.

In [11]:
arr.ndim

1

In [12]:
l = [1, 2, 3, 4, 5, "Rishi"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U21')

In [13]:
arr.ndim

1

In [14]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr1.ndim

2

In [17]:
l = [1,2,3,4]

In [18]:
mat = np.matrix(l) #Matrix will be by default 2D

In [19]:
np.matrix([[[1,2],[5,6],[7,8]]])

ValueError: matrix must be 2-dimensional

In [ ]:
np.array([[[1,2],[5,6],[7,8]]])

In [20]:
#more way to convert an array
np.asarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [21]:
np.asanyarray([[[1,2],[3,4],[5,6]]]) #Convert the input to an ndarray, but pass ndarray subclass

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [22]:
mat

matrix([[1, 2, 3, 4]])

In [23]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [24]:
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [25]:
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [26]:
t = ([1,2,3], [4,5,6])
type(t)

tuple

In [27]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a = 5
np.array(a)

array(5)

In [29]:
#Break for 10 minute

In [30]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [31]:
arr[3]

4

In [32]:
#Deep and Shallow copy
#Shallow copy
a = arr

In [33]:
a

array([1, 2, 3, 4, 5])

In [34]:
arr[0]=100

In [35]:
arr

array([100,   2,   3,   4,   5])

In [36]:
a

array([100,   2,   3,   4,   5])

In [37]:
#Deep copy
b = a.copy()

In [38]:
b

array([100,   2,   3,   4,   5])

In [39]:
a[0] = 2000

In [40]:
a

array([2000,    2,    3,    4,    5])

In [41]:
b

array([100,   2,   3,   4,   5])

In [42]:
#to create array >> .array, .asarray, .asanyarray, deep copy, shallow copy
#There are multiple ways to generate array

In [43]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr.shape

(5,)

In [46]:
arr1.shape

(2, 3)

In [47]:
arr.size

5

In [48]:
arr1.size

6

In [49]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [50]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [53]:
for i in range(5):
    print(i)

0
1
2
3
4


In [54]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [55]:
list(range(5))

[0, 1, 2, 3, 4]

In [58]:
iterable=(i*i for i in range(5))

In [59]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [60]:
np.fromstring("23 34 67", sep = ' ')

array([23., 34., 67.])

In [63]:
np.fromstring('23,34,67', sep = ',')

array([23., 34., 67.])

In [64]:
np.fromstring("Suhani, Ajay,Anwesha", sep = ',')

/tmp/ipykernel_77/1396631115.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("Suhani, Ajay,Anwesha", sep = ',')


array([], dtype=float64)

In [65]:
arr

array([2000,    2,    3,    4,    5])

In [66]:
arr.size

5

In [67]:
arr.shape

(5,)

In [68]:
arr.dtype

dtype('int64')

In [70]:
l = [1,2,3, "Ajay"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [71]:
arr

array(['1', '2', '3', 'Ajay'], dtype='<U21')

In [72]:
list(range(5))

[0, 1, 2, 3, 4]

In [73]:
range(5)

range(0, 5)

In [77]:
list(range(1.0,2.10)) #Range can not deal with Float

TypeError: 'float' object cannot be interpreted as an integer

In [81]:
list(np.arange(0.1,10.2,0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [88]:
np.linspace(1,5,40) #AP

array([1.        , 1.1025641 , 1.20512821, 1.30769231, 1.41025641,
       1.51282051, 1.61538462, 1.71794872, 1.82051282, 1.92307692,
       2.02564103, 2.12820513, 2.23076923, 2.33333333, 2.43589744,
       2.53846154, 2.64102564, 2.74358974, 2.84615385, 2.94871795,
       3.05128205, 3.15384615, 3.25641026, 3.35897436, 3.46153846,
       3.56410256, 3.66666667, 3.76923077, 3.87179487, 3.97435897,
       4.07692308, 4.17948718, 4.28205128, 4.38461538, 4.48717949,
       4.58974359, 4.69230769, 4.79487179, 4.8974359 , 5.        ])

In [89]:
np.logspace(1,5,10,base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [90]:
np.logspace(1,5,10,base = 10) #Log value

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [101]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [102]:
arr2 = np.zeros((3,4))
arr2.shape

(3, 4)

In [103]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
arr2.ndim

2

In [107]:
arr3 = np.zeros((3,3,4))
arr3.shape

(3, 3, 4)

In [108]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [109]:
arr3.ndim

3

In [114]:
arr4 = np.zeros((1,3,3,4))
arr4.shape

(1, 3, 3, 4)

In [116]:
arr4.ndim

4

In [117]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [118]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [120]:
arr = np.ones((3,4))

In [123]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [124]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [125]:
arr*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [126]:
'''Array contains same data while list containe heterogeneous, also memory allocation hence the array
is faster than list.(Concept of referencing)
'''
#Python has automatic grabage removal
#Resizing:- list.append
#Array is statically defined(not dynamic), no concept of resizing
#1D Array->vector
#2D Array->Metrix
#3D Array->tensor

#Vectorization: 

'Array contains same data while list containe heterogeneous, also memory allocation hence the array\nis faster than list.(Concept of referencing)\n'

In [1]:
"""NumPy - Numerical python
Jan 21^24:- Second class for Numpy(NumPy Advance)"""

'NumPy - Numerical python\nJan 21^24:- Second class for Numpy(NumPy Advance)'

In [2]:
import numpy as np
arr = np.ones((3,4))

In [3]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [5]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [6]:
np.empty((3,4)) #Any random value

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [7]:
np.eye(3, dtype=int) #n*n matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#Optional
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [10]:
#Extra topics
import random

In [11]:
random.choice((1,2,3,4,5,6))

3

In [12]:
random.choice("Ajay")

'y'

In [13]:
random.randrange(1,1000)

868

In [14]:
random.randrange(1,1000,)

763

In [15]:
random.random() #a random number is generated between 0(include), and 1(excluded)

0.6954014676645762

In [16]:
lis = [1,2,3,4,5]
random.shuffle(lis)

In [17]:
lis

[1, 2, 4, 5, 3]

In [18]:
random.uniform(7,14) #a number between 7 and 14 having uniform probability

8.301250700082086

In [19]:
#Continue with NumPy

In [20]:
np.random.rand(1)

array([0.62345255])

In [21]:
np.random.rand(2,3)

array([[0.55167224, 0.54193781, 0.57894948],
       [0.25081575, 0.07789974, 0.52371716]])

In [22]:
np.random.randn(2,3)

array([[-1.35534377,  1.5832594 ,  0.51810757],
       [-0.55931225, -1.15423854, -0.70154711]])

In [23]:
np.random.random_sample()

0.22991907143903978

In [24]:
arr = np.random.randint(1,5, size=(3,4))

In [25]:
arr

array([[2, 1, 1, 3],
       [1, 4, 1, 4],
       [1, 3, 1, 3]])

In [26]:
arr.size

12

In [27]:
arr.shape

(3, 4)

In [28]:
arr.ndim

2

In [29]:
arr.reshape(3,4) #Array size can not change, so the input numbers should be factors of size.

array([[2, 1, 1, 3],
       [1, 4, 1, 4],
       [1, 3, 1, 3]])

In [30]:
arr.reshape(4,3)

array([[2, 1, 1],
       [3, 1, 4],
       [1, 4, 1],
       [3, 1, 3]])

In [31]:
arr.reshape(4,-1)

array([[2, 1, 1],
       [3, 1, 4],
       [1, 4, 1],
       [3, 1, 3]])

In [32]:
arr.reshape(3,-1)

array([[2, 1, 1, 3],
       [1, 4, 1, 4],
       [1, 3, 1, 3]])

In [33]:
arr.reshape(-1,6)

array([[2, 1, 1, 3, 1, 4],
       [1, 4, 1, 3, 1, 3]])

In [34]:
arr.reshape(12,1).base

array([[2, 1, 1, 3],
       [1, 4, 1, 4],
       [1, 3, 1, 3]])

In [35]:
#Break for 10 minutes

In [36]:
arr.reshape(2,2,3)

array([[[2, 1, 1],
        [3, 1, 4]],

       [[1, 4, 1],
        [3, 1, 3]]])

In [37]:
arr.reshape(4,3,1)

array([[[2],
        [1],
        [1]],

       [[3],
        [1],
        [4]],

       [[1],
        [4],
        [1]],

       [[3],
        [1],
        [3]]])

In [38]:
arr.reshape(1,1,1,1,1,2,2,3)

array([[[[[[[[2, 1, 1],
             [3, 1, 4]],

            [[1, 4, 1],
             [3, 1, 3]]]]]]]])

In [39]:
list = [1,2,3,4]
arr = np.array(lis)

In [40]:
arr.ndim

1

In [41]:
arr2 = np.array([[2,3],[4,5]])
arr2

array([[2, 3],
       [4, 5]])

In [42]:
arr2.ndim

2

In [43]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr2.ndim

2

In [45]:
arr3 = np.zeros((1,3,4)) # 3 rows, 4 columns >> 2D array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [46]:
arr3.ndim

3

In [47]:
arr3.shape

(1, 3, 4)

In [48]:
arr4 = np.zeros((1,1,3,4)) # 3 rows, 4 columns >> 2D array + 1d+1d
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [49]:
arr4.ndim

4

In [50]:
arr4.shape

(1, 1, 3, 4)

In [51]:
arr3 = np.zeros((3,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
arr3.ndim

3

In [53]:
arr3.shape

(3, 3, 4)

In [54]:
arr1 = np.random.randint(1,10,(5,6))

In [55]:
arr1

array([[8, 6, 6, 2, 5, 1],
       [9, 7, 7, 3, 4, 4],
       [4, 8, 1, 8, 7, 4],
       [4, 8, 5, 8, 6, 3],
       [3, 8, 3, 1, 7, 2]])

In [56]:
arr1>5

array([[ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [False,  True, False,  True,  True, False],
       [False,  True, False,  True,  True, False],
       [False,  True, False, False,  True, False]])

In [57]:
arr1[arr1>5]

array([8, 6, 6, 9, 7, 7, 8, 8, 7, 8, 8, 6, 8, 7])

In [58]:
arr1[arr1<5]

array([2, 1, 3, 4, 4, 4, 1, 4, 4, 3, 3, 3, 1, 2])

In [59]:
arr

array([1, 2, 4, 5, 3])

In [60]:
arr[0]

1

In [61]:
arr[1]

2

In [62]:
arr1

array([[8, 6, 6, 2, 5, 1],
       [9, 7, 7, 3, 4, 4],
       [4, 8, 1, 8, 7, 4],
       [4, 8, 5, 8, 6, 3],
       [3, 8, 3, 1, 7, 2]])

In [63]:
arr1[0]

array([8, 6, 6, 2, 5, 1])

In [64]:
arr1[0][0]

8

In [65]:
arr1[0][1:3]

array([6, 6])

In [66]:
arr1[0, [1,3]]

array([6, 2])

In [67]:
arr1[2:4]

array([[4, 8, 1, 8, 7, 4],
       [4, 8, 5, 8, 6, 3]])

In [68]:
arr1[2:4, [0,2]]

array([[4, 1],
       [4, 5]])

In [69]:
arr1

array([[8, 6, 6, 2, 5, 1],
       [9, 7, 7, 3, 4, 4],
       [4, 8, 1, 8, 7, 4],
       [4, 8, 5, 8, 6, 3],
       [3, 8, 3, 1, 7, 2]])

In [70]:
arr1[2:5]

array([[4, 8, 1, 8, 7, 4],
       [4, 8, 5, 8, 6, 3],
       [3, 8, 3, 1, 7, 2]])

In [71]:
arr1[2:5,[0,2]] #Slicing in array

array([[4, 1],
       [4, 5],
       [3, 3]])

In [72]:
arr1[[2,4],[0,2]]

array([4, 3])

In [73]:
arr1[[2,4]] #selecting specific column

array([[4, 8, 1, 8, 7, 4],
       [3, 8, 3, 1, 7, 2]])

In [74]:
arr1[2:4] #slicing

array([[4, 8, 1, 8, 7, 4],
       [4, 8, 5, 8, 6, 3]])

In [75]:
arr1

array([[8, 6, 6, 2, 5, 1],
       [9, 7, 7, 3, 4, 4],
       [4, 8, 1, 8, 7, 4],
       [4, 8, 5, 8, 6, 3],
       [3, 8, 3, 1, 7, 2]])

In [76]:
arr1[2:4, [1,3]]

array([[8, 8],
       [8, 8]])

In [77]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [78]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [79]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [80]:
arr1+arr2

array([[4, 3, 4],
       [4, 4, 4],
       [2, 4, 2]])

In [81]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [82]:
arr1*arr2

array([[4, 2, 4],
       [4, 4, 4],
       [1, 4, 1]])

In [83]:
#Matrix multiplication
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [84]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [85]:
arr1@arr2

array([[ 8, 10,  8],
       [10, 12, 10],
       [ 7,  8,  7]])

In [86]:
arr1/arr2 #index wise division

array([[1. , 0.5, 1. ],
       [1. , 1. , 1. ],
       [1. , 1. , 1. ]])

In [87]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [88]:
arr1/0

/tmp/ipykernel_84/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [89]:
#Broad Casting after break

In [90]:
#Broad Casting
arr = np.zeros([3,4])

In [91]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [93]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
a = np.array([1,2,3,4])

In [95]:
a

array([1, 2, 3, 4])

In [96]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [97]:
a = np.array([1,2,3])

In [98]:
a

array([1, 2, 3])

In [99]:
arr+a

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.array([[1,2,3]])

In [ ]:
a

In [ ]:
a.T #Transpose

In [ ]:
arr

In [ ]:
a

In [100]:
arr+a.T

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [101]:
a = np.array([1,2,3])
a.T

array([1, 2, 3])

In [102]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [103]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [104]:
np.log10(arr1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ]])

In [105]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [106]:
a

array([1, 2, 3])

In [107]:
np.min(a)

1

In [108]:
np.min(arr1)

1

In [109]:
np.max(a)

3

In [110]:
arr1.T

array([[2, 2, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [111]:
arr1.flatten() #Reduce higher demension to 1d

array([2, 1, 2, 2, 2, 2, 1, 2, 1])

In [112]:
#Expand_dimension >> expands the array by inserting a new axis

In [113]:
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [114]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [115]:
np.sum(arr)

27

In [116]:
np.sum(arr,axis=0)

array([ 6,  9, 12])

In [117]:
np.sum(arr,axis=1)

array([ 6, 15,  6])

In [120]:
#Expand_dims>>expand the dimension of array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [121]:
arr.ndim

1

In [122]:
arr1 = np.expand_dims(arr, axis = 0)

In [123]:
arr1.ndim

2

In [124]:
arr2  =np.expand_dims(arr1,axis=0)
arr2

array([[[1, 2, 3, 4]]])

In [125]:
arr2.shape

(1, 1, 4)

In [127]:
arr1 = np.expand_dims(arr,axis=1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [129]:
arr = np.zeros((3,4))

In [130]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
arr1 = np.expand_dims(arr,axis=1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [132]:
#Done with today's class...

In [1]:
"""NumPy - Numerical python
3rd_Feb^24:- Third class for Numpy(NumPy Advance)"""

'NumPy - Numerical python\n3rd_Feb^24:- Third class for Numpy(NumPy Advance)'

In [7]:
import numpy as np
data = np.array([[1],[2],[3]])

In [8]:
data

array([[1],
       [2],
       [3]])

In [9]:
data.ndim

2

In [12]:
a = np.squeeze(data)

In [13]:
a.ndim

1

In [14]:
#repeat
data

array([[1],
       [2],
       [3]])

In [15]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
a = np.array([[1,2],[3,4]])

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [20]:
a

array([[1, 2],
       [3, 4]])

In [19]:
np.repeat(a,2,axis=1) #Repeat column wise

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [22]:
np.repeat(a,2,axis = 0) #Repeat Row wise

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [23]:
data

array([[1],
       [2],
       [3]])

In [24]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [25]:
np.roll(data,-2)

array([[3],
       [1],
       [2]])

In [26]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
a = np.array([[[1,2],[3,4],[5,6]]])

In [29]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [32]:
np.roll(a,2,axis=0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [33]:
#Binary Operation on array

In [34]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [37]:
arr1

array([[3, 8, 8, 1],
       [4, 9, 2, 3],
       [8, 8, 8, 4]])

In [38]:
arr2

array([[1, 5, 7, 5],
       [9, 4, 2, 5],
       [8, 7, 8, 2]])

In [39]:
arr1+arr2

array([[ 4, 13, 15,  6],
       [13, 13,  4,  8],
       [16, 15, 16,  6]])

In [40]:
arr1*arr2

array([[ 3, 40, 56,  5],
       [36, 36,  4, 15],
       [64, 56, 64,  8]])

In [41]:
arr1/arr2

array([[3.        , 1.6       , 1.14285714, 0.2       ],
       [0.44444444, 2.25      , 1.        , 0.6       ],
       [1.        , 1.14285714, 1.        , 2.        ]])

In [42]:
arr1-arr2

array([[ 2,  3,  1, -4],
       [-5,  5,  0, -2],
       [ 0,  1,  0,  2]])

In [43]:
arr1**arr2

array([[       3,    32768,  2097152,        1],
       [  262144,     6561,        4,      243],
       [16777216,  2097152, 16777216,       16]])

In [44]:
arr1>arr2

array([[ True,  True,  True, False],
       [False,  True, False, False],
       [False,  True, False,  True]])

In [45]:
~arr1

array([[ -4,  -9,  -9,  -2],
       [ -5, -10,  -3,  -4],
       [ -9,  -9,  -9,  -5]])

In [46]:
arr1

array([[3, 8, 8, 1],
       [4, 9, 2, 3],
       [8, 8, 8, 4]])

In [47]:
#Numpy String Function

In [48]:
arr = np.array(["pw","Skills"])

In [49]:
arr

array(['pw', 'Skills'], dtype='<U6')

In [50]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [52]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [53]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [54]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [55]:
#Mathematical Funcion

arr1

array([[3, 8, 8, 1],
       [4, 9, 2, 3],
       [8, 8, 8, 4]])

In [56]:
np.sin(arr1)

array([[ 0.14112001,  0.98935825,  0.98935825,  0.84147098],
       [-0.7568025 ,  0.41211849,  0.90929743,  0.14112001],
       [ 0.98935825,  0.98935825,  0.98935825, -0.7568025 ]])

In [57]:
np.cos(arr1)

array([[-0.9899925 , -0.14550003, -0.14550003,  0.54030231],
       [-0.65364362, -0.91113026, -0.41614684, -0.9899925 ],
       [-0.14550003, -0.14550003, -0.14550003, -0.65364362]])

In [58]:
np.log10(arr1)

array([[0.47712125, 0.90308999, 0.90308999, 0.        ],
       [0.60205999, 0.95424251, 0.30103   , 0.47712125],
       [0.90308999, 0.90308999, 0.90308999, 0.60205999]])

In [59]:
np.exp(arr1)

array([[2.00855369e+01, 2.98095799e+03, 2.98095799e+03, 2.71828183e+00],
       [5.45981500e+01, 8.10308393e+03, 7.38905610e+00, 2.00855369e+01],
       [2.98095799e+03, 2.98095799e+03, 2.98095799e+03, 5.45981500e+01]])

In [61]:
np.power(arr1,2)

array([[ 9, 64, 64,  1],
       [16, 81,  4,  9],
       [64, 64, 64, 16]])

In [62]:
np.mean(arr1)

5.5

In [63]:
np.max(arr1)

9

In [64]:
np.std(arr1)

2.7838821814150108

In [65]:
np.var(arr1)

7.75

In [66]:
arr1-arr2

array([[ 2,  3,  1, -4],
       [-5,  5,  0, -2],
       [ 0,  1,  0,  2]])

In [67]:
np.subtract(arr1,arr2)

array([[ 2,  3,  1, -4],
       [-5,  5,  0, -2],
       [ 0,  1,  0,  2]])

In [68]:
arr1*arr2

array([[ 3, 40, 56,  5],
       [36, 36,  4, 15],
       [64, 56, 64,  8]])

In [69]:
np.multiply(arr1,arr2)

array([[ 3, 40, 56,  5],
       [36, 36,  4, 15],
       [64, 56, 64,  8]])

In [72]:
np.mod(arr1,arr2) #Return element wise remainder

array([[0, 3, 1, 1],
       [4, 1, 0, 3],
       [0, 1, 0, 0]])

In [73]:
np.power(arr1,arr2)

array([[       3,    32768,  2097152,        1],
       [  262144,     6561,        4,      243],
       [16777216,  2097152, 16777216,       16]])

In [74]:
np.sqrt(arr1)

array([[1.73205081, 2.82842712, 2.82842712, 1.        ],
       [2.        , 3.        , 1.41421356, 1.73205081],
       [2.82842712, 2.82842712, 2.82842712, 2.        ]])

In [75]:
#Sorting and Searching

In [76]:
arr = np.array([5,6,1,2])

In [77]:
arr

array([5, 6, 1, 2])

In [78]:
np.sort(arr)

array([1, 2, 5, 6])

In [96]:
arr1 = np.array([5,6,100,200,1,2,8,9])

In [97]:
#a = np.sort(arr1)

In [98]:
arr1

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [100]:
np.searchsorted(arr1,3)

6

In [79]:
np.searchsorted(arr,3)

4

In [83]:
arr = np.array([0,1,2,3,0,4])
np.count_nonzero(arr)

4

In [84]:
arr>0

array([False,  True,  True,  True, False,  True])

In [85]:
np.where(arr>0)

(array([1, 2, 3, 5]),)

In [87]:
np.extract(arr>0,arr)

array([1, 2, 3, 4])

In [104]:
arr

array([0, 1, 2, 3, 0, 4])

In [105]:
arr.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808,                  0, 288230376151711744])

In [106]:
#Matrix >> 2D array

In [107]:
import numpy.matlib as nm

In [108]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [109]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [110]:
#Numpy linear Algebra

In [111]:
arr1

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [117]:
arr1 = np.array([[2,3],[4,5]])
arr2 = np.array([[1,3],[4,5]])

In [118]:
arr1

array([[2, 3],
       [4, 5]])

In [119]:
arr2

array([[1, 3],
       [4, 5]])

In [120]:
arr1@arr2

array([[14, 21],
       [24, 37]])

In [128]:
#7x+5y-3z = 16, 2x-5y+2z = -8, 5x+3y-7z = 0
a = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [129]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [130]:
b = np.array([16,-8,0])

In [131]:
b

array([16, -8,  0])

In [132]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [133]:
arr1

array([[2, 3],
       [4, 5]])

In [134]:
5*2-4*3

-2

In [135]:
np.linalg.det(arr1)

-2.0

In [136]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [137]:
#Done with Numpy...(Completed)...